import { defineConfig } from "vitepress";

export default defineConfig({
  title: "Cocoa Discord",
  description:
    "Documentation for Cocoa Discord, Library to simplify creating discord bots",
  lastUpdated: true,

  themeConfig: {
    footer: {
      message:
        "Documentation generated by Vitepress. This project/library is released under the MIT License",
      copyright: "Copyright © 2022-2023 Leomotors",
    },
    socialLinks: [
      {
        icon: "github",
        link: "https://github.com/Leomotors/cocoa-discord",
      },
    ],
    editLink: {
      pattern:
        "https://github.com/Leomotors/cocoa-discord/edit/main/docs/:path",
      text: "Suggest or contribute changes to this page",
    },

    nav: [
      {
        text: "Changelog",
        link: "/changelog",
      },
      {
        text: "TypeDoc",
        link: "https://cocoa.leomotors.me/typedoc",
      },
    ],
    sidebar: [
      {
        collapsed: true,
        text: "Blog",
        items: [
          {
            text: "About this Website",
            link: "/blog/about",
          },
          {
            text: "Introducing V2",
            link: "/blog/introducing-v2",
          },
        ],
      },
      {
        collapsed: true,
        text: "Introduction",
        items: [
          {
            text: "Overview",
            link: "/introduction/overview",
          },
          {
            text: "Examples",
            link: "/introduction/examples",
          },
          {
            text: "TypeDoc",
            link: "https://cocoa.leomotors.me/typedoc",
          },
          {
            text: "Migration Guide",
            link: "/introduction/migrate",
          },
        ],
      },
      {
        collapsed: true,
        text: "Release Changelog",
        items: [
          {
            text: "Cocoa Discord",
            link: "/changelog/cocoa-discord",
          },
          {
            text: "Music Module",
            link: "/changelog/music-module",
          },
        ],
      },
      {
        collapsed: true,
        text: "Cocoa Discord Package",
        items: [
          {
            text: "Main",
            link: "/main-package/main",
          },
          {
            text: "Meta",
            link: "/main-package/meta",
          },
          {
            text: "Template",
            link: "/main-package/template",
          },
          {
            text: "Message & Slash",
            link: "/main-package/msgslash",
          },
        ],
      },
      {
        collapsed: true,
        text: "Command Management System",
        items: [
          {
            text: "Basic Concept",
            link: "/cms/basic",
          },
          {
            text: "Advanced Decorator Syntax",
            link: "/cms/decorator",
          },
          {
            text: "Specific-Guild Command",
            link: "/cms/guild",
          },
          {
            text: "Message Commands",
            link: "/cms/message",
          },
          {
            text: "Other Utilities",
            link: "/cms/other",
          },

          {
            text: "Event Handling",
            link: "/cms/event",
          },
        ],
      },
      {
        collapsed: true,
        text: "Music Module",
        items: [
          {
            text: "Introduction",
            link: "/music-module/intro",
          },
        ],
      },
    ],
  },

  outDir: "../docs-dist",
});
