name: Test

on:
  push:

jobs:
  main:
    name: Mocha
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Config Package (Just In Case)
        run: yarn lm:config
      - name: Mocha Test
        run: yarn test
