name: Caffe Mocha

on:
  push:

jobs:
  main:
    name: Iroiro na Test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Build Test
        run: yarn build
      - name: ESLint & Prettier Check
        run: yarn lint
      - name: Mocha Test, Actually it is now Jest
        run: yarn test
      - name: Generating Documents Test
        run: yarn docs
      - name: CRLF Phobia
        run: npx crlf-phobia *
