name: Iroiro na Test

on:
  push:

jobs:
  lint:
    name: Linting Test
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: ESLint & Prettier Check
        run: yarn lint
      - name: CRLF Phobia
        run: npx crlf-phobia *
  
  docs:
    name: Docs Gen Test
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Generating Documents Test
        run: yarn docs

  caffe-mocha:
    name: Caffe Mocha Test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Run Pre-Build Tasks
        run: yarn lm:config
      - name: Mocha Test, Actually it is now Jest, and just switched to Vitest
        run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
