name: Iroiro na Test

on:
  push:

jobs:
  lint:
    name: Linting Test
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: ESLint & Prettier Check
        run: pnpm lint

      - name: CRLF Phobia
        run: npx crlf-phobia *

  docs:
    name: Docs Gen Test
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build all Package
        run: pnpm run build

      - name: Generating Documents Test
        run: pnpm run docs

  caffe-mocha:
    name: Caffe Mocha Test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2

    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build all Package
        run: pnpm run build

      - name: Mocha Test, Actually it is now Jest, and just switched to Vitest
        run: pnpm run test
