# * Original: https://github.com/discordjs/voice/blob/main/.github/workflows/docs.yml

name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - apps/docs/**
      - packages/*/CHANGELOG.md

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build all Package
        run: pnpm run build

      - name: Build documentation
        run: pnpm run docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
