# * Original: https://github.com/discordjs/voice/blob/main/.github/workflows/docs.yml

name: Documentation

on:
  push:
    tags:
      # - "[0-9]+.[0-9]+.[0-9]+" (After 2.0 is released, will switch to this)
      - "*.*"

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies (Yarn)
        run: yarn install

      - name: Build documentation
        run: yarn docs

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs-dist
